### ISSUE TITLE
Bug - new java

### ISSUE THREAD

**Issue by eloe79** [DenisMasterHerobrine/TravellersBoots#8]
Minecraft Version: 1.15.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_241, Oracle Corporation
ModLauncher: 5.0.0-milestone.4+67+b1a340b
Forge: net.minecraftforge:31.1.27

Bug:
[Forge Version Check/INFO]: [travellersboots] Starting version check at http:/myurl.me/
[Forge Version Check/WARN]: Failed to process update information
java.lang.RuntimeException: java.lang.IllegalArgumentException: protocol = http host = null
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_241]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_241]
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(Unknown Source) ~[?:1.8.0_241]
	at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.VersionChecker$1.openUrlStream(VersionChecker.java:173) ~[?:?]
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:206) ~[?:?]
	at java.lang.Iterable.forEach(Unknown Source) [?:1.8.0_241]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:157) [?:?]
Caused by: java.lang.IllegalArgumentException: protocol = http host = null
	at sun.net.spi.DefaultProxySelector.select(Unknown Source) ~[?:1.8.0_241]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:1.8.0_241]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:1.8.0_241]
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[?:1.8.0_241]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_241]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_241]
	... 5 more

**Comment by DenisMasterHerobrine** [comment]
This is a known issue, which shouldn't affect your game/modpack as I know. It's a crash or just a warning in the logs? I can fix this soon, if this causes some problems with other mods or crashes your modpack.
(But, this is just a version check failing to process the default example forge URL)

**Comment by eloe79** [comment]
not sure, for moment is working fine, just reported as good did :D
from my own experience, is better to report stuff and not use then just have nothing to work on
will try again today, meaning will try to use this botts and see what happens, i have it in pack, and so far didnt gave me more trouble

**Comment by DenisMasterHerobrine** [comment]
Finally fixed in 1.5.0.
